global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ms-auth'
    static_configs:
      - targets: ['msauth:8080']
    metrics_path: '/metrics'
  
  - job_name: 'ms-projects'
    static_configs:
      - targets: ['msprojects:8080']
    metrics_path: '/metrics'
  
  - job_name: 'ms-tasks'
    static_configs:
      - targets: ['mstasks:8080']
    metrics_path: '/metrics'
  
  - job_name: 'ms-notifications'
    static_configs:
      - targets: ['msnotifications:8080']
    metrics_path: '/metrics'
  
  - job_name: 'ms-gateway'
    static_configs:
      - targets: ['msgateway:8080']
    metrics_path: '/metrics'
